version: "3.7"

services:

  web:
    build: ./locations
    container_name: locations_web
    ports:
      - 8000:8000
    network_mode: "host"
    restart: always
    environment:
      USER_NAME: ${USER_NAME}
      USER_PASSWORD: ${USER_PASSWORD}
      BASE_NAME: locations_db
      PORT: ${PORT}

  db:
    image: postgres
    ports:
      - ${PORT}:5432
    environment:
      POSTGRES_USER: ${USER_NAME}
      POSTGRES_PASSWORD: ${USER_PASSWORD}
      POSTGRES_DB: locations_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    restart: always
